### ISSUE TITLE
Set up Locally with PostgreSQL

### ISSUE THREAD

**Issue by Camper94** [GoldenThrust/Virtual-Bank#11]
For those who want to test the application locally with PostgreSQL, you can configure access to the database by adding these lines to the .env file:
`# .env file for local PostgreSQL
DB_USER=your_db_username
DB_PASSWORD=your_db_password
DB_HOST=localhost
DB_PORT=5432
DB_NAME=virtualbank
`
However, you might encounter the "No migrations to apply" message when running the command:
`python3 manage.py migrate`

To resolve this issue, navigate to api/virtual_bank/settings.py and modify the DATABASES variable on line 105 by removing the section responsible for testing and connecting to the Neon Database. The updated configuration should look like this:
`DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': os.getenv('DB_NAME'), 
    'USER': os.getenv('DB_USER'), 
    'PASSWORD': os.getenv('DB_PASSWORD'), 
    'HOST':  os.getenv('DB_HOST'), 
    'PORT':  os.getenv('DB_PORT'),
    'OPTIONS': {} if DEBUG else {
      'sslmode': 'require',
    },
  }
}
`

**Comment by GoldenThrust** [comment]
I will work on this.
